// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHcCGHzAv7CouYo27pDr-7ENO75MDoxc',
    appId: '1:891296947456:web:2d4b3f9b8e814cb06167e5',
    messagingSenderId: '891296947456',
    projectId: 'groceryapp1997',
    authDomain: 'groceryapp1997.firebaseapp.com',
    storageBucket: 'groceryapp1997.appspot.com',
    measurementId: 'G-8PKFBVS3SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJkVaO28W2imcjgUmN86dTWdL8jFHMWQ',
    appId: '1:891296947456:android:61a7e7f74fd000706167e5',
    messagingSenderId: '891296947456',
    projectId: 'groceryapp1997',
    storageBucket: 'groceryapp1997.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxHcCGHzAv7CouYo27pDr-7ENO75MDoxc',
    appId: '1:891296947456:web:5a55696dd2d078266167e5',
    messagingSenderId: '891296947456',
    projectId: 'groceryapp1997',
    authDomain: 'groceryapp1997.firebaseapp.com',
    storageBucket: 'groceryapp1997.appspot.com',
    measurementId: 'G-2LZZ6THLD9',
  );
}
